/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/NpHvWTaA1Gh
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"

export function Orders() {
  const orders = [
    {
      id: "ORD001",
      customer: "John Doe",
      product: "Wireless Headphones",
      quantity: 2,
      date: "2023-06-01",
      status: "Delivered",
      amount: 149.99,
    },
    {
      id: "ORD002",
      customer: "Jane Smith",
      product: "Fitness Tracker",
      quantity: 1,
      date: "2023-06-03",
      status: "Shipped",
      amount: 79.99,
    },
    {
      id: "ORD003",
      customer: "Michael Johnson",
      product: "Smart TV",
      quantity: 1,
      date: "2023-06-05",
      status: "Pending",
      amount: 499.99,
    },
    {
      id: "ORD004",
      customer: "Emily Brown",
      product: "Laptop Sleeve",
      quantity: 3,
      date: "2023-06-07",
      status: "Delivered",
      amount: 59.97,
    },
    {
      id: "ORD005",
      customer: "David Lee",
      product: "Wireless Mouse",
      quantity: 1,
      date: "2023-06-09",
      status: "Shipped",
      amount: 29.99,
    },
    {
      id: "ORD006",
      customer: "Sarah Kim",
      product: "Portable Charger",
      quantity: 2,
      date: "2023-06-11",
      status: "Delivered",
      amount: 49.98,
    },
    {
      id: "ORD007",
      customer: "Alex Chen",
      product: "Gaming Keyboard",
      quantity: 1,
      date: "2023-06-13",
      status: "Pending",
      amount: 99.99,
    },
    {
      id: "ORD008",
      customer: "Olivia Patel",
      product: "Wireless Earbuds",
      quantity: 1,
      date: "2023-06-15",
      status: "Delivered",
      amount: 129.99,
    },
  ]
  const totalOrders = orders.length
  const totalRevenue = orders.reduce((acc, order) => acc + order.amount, 0)
  const averageOrderValue = totalRevenue / totalOrders
  return (
    <div className="container mx-auto px-4 md:px-6 py-8">
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
        <Card>
          <CardHeader>
            <CardTitle>Total Orders</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-4xl font-bold">{totalOrders}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Total Revenue</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-4xl font-bold">${totalRevenue.toFixed(2)}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Average Order Value</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-4xl font-bold">${averageOrderValue.toFixed(2)}</div>
          </CardContent>
        </Card>
      </div>
      <div className="mt-8">
        <Card>
          <CardHeader>
            <CardTitle>Recent Orders</CardTitle>
          </CardHeader>
          <CardContent>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Order #</TableHead>
                  <TableHead>Customer</TableHead>
                  <TableHead>Product</TableHead>
                  <TableHead>Quantity</TableHead>
                  <TableHead>Date</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead className="text-right">Amount</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {orders.map((order) => (
                  <TableRow key={order.id}>
                    <TableCell>{order.id}</TableCell>
                    <TableCell>{order.customer}</TableCell>
                    <TableCell>{order.product}</TableCell>
                    <TableCell>{order.quantity}</TableCell>
                    <TableCell>{order.date}</TableCell>
                    <TableCell>
                      <Badge
                        variant={
                          order.status === "Delivered"
                            ? "secondary"
                            : order.status === "Shipped"
                            ? "outline"
                            : "default"
                        }
                      >
                        {order.status}
                      </Badge>
                    </TableCell>
                    <TableCell className="text-right">${order.amount.toFixed(2)}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
