/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Hy67h66nYvq
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"

export function testimonials() {
  return (
    <section className="bg-background py-12 md:py-16 lg:py-20">
      <div className="container mx-auto px-4 md:px-6">
        <div className="mb-8 md:mb-12 lg:mb-16">
          <h2 className="text-2xl font-bold md:text-3xl lg:text-4xl">What Our Customers Say</h2>
        </div>
        <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
          <div className="flex flex-col items-start rounded-lg bg-card p-6 shadow-lg transition-all duration-300 hover:shadow-xl">
            <div className="mb-4 flex items-center justify-between w-full">
              <div className="flex items-center gap-2">
                <Avatar className="h-10 w-10 border">
                  <AvatarImage src="/placeholder-user.jpg" />
                  <AvatarFallback>CN</AvatarFallback>
                </Avatar>
                <div>
                  <h3 className="text-base font-semibold">Sarah Johnson</h3>
                  <p className="text-sm text-muted-foreground">CEO, Acme Inc</p>
                </div>
              </div>
              <div className="flex items-center gap-1">
                <StarIcon className="h-5 w-5 fill-primary" />
                <StarIcon className="h-5 w-5 fill-primary" />
                <StarIcon className="h-5 w-5 fill-primary" />
                <StarIcon className="h-5 w-5 fill-primary" />
                <StarIcon className="h-5 w-5 fill-primary" />
              </div>
            </div>
            <p className="text-sm leading-relaxed text-muted-foreground">
              "I've been using this product for months and it has completely\n transformed my workflow. The intuitive
              design and powerful\n features have made my job so much easier."
            </p>
          </div>
          <div className="flex flex-col items-start rounded-lg bg-card p-6 shadow-lg transition-all duration-300 hover:shadow-xl">
            <div className="mb-4 flex items-center justify-between w-full">
              <div className="flex items-center gap-2">
                <Avatar className="h-10 w-10 border">
                  <AvatarImage src="/placeholder-user.jpg" />
                  <AvatarFallback>CN</AvatarFallback>
                </Avatar>
                <div>
                  <h3 className="text-base font-semibold">Alex Smith</h3>
                  <p className="text-sm text-muted-foreground">Product Manager, Globex Inc</p>
                </div>
              </div>
              <div className="flex items-center gap-1">
                <StarIcon className="h-5 w-5 fill-primary" />
                <StarIcon className="h-5 w-5 fill-primary" />
                <StarIcon className="h-5 w-5 fill-primary" />
                <StarIcon className="h-5 w-5 fill-primary" />
                <StarIcon className="h-5 w-5 fill-primary" />
              </div>
            </div>
            <p className="text-sm leading-relaxed text-muted-foreground">
              "This product has been a game-changer for my team. The\n collaboration features and seamless integration
              have made our\n workflow so much more efficient."
            </p>
          </div>
          <div className="flex flex-col items-start rounded-lg bg-card p-6 shadow-lg transition-all duration-300 hover:shadow-xl">
            <div className="mb-4 flex items-center justify-between w-full">
              <div className="flex items-center gap-2">
                <Avatar className="h-10 w-10 border">
                  <AvatarImage src="/placeholder-user.jpg" />
                  <AvatarFallback>CN</AvatarFallback>
                </Avatar>
                <div>
                  <h3 className="text-base font-semibold">Emily Parker</h3>
                  <p className="text-sm text-muted-foreground">Marketing Manager, Stark Industries</p>
                </div>
              </div>
              <div className="flex items-center gap-1">
                <StarIcon className="h-5 w-5 fill-primary" />
                <StarIcon className="h-5 w-5 fill-primary" />
                <StarIcon className="h-5 w-5 fill-primary" />
                <StarIcon className="h-5 w-5 fill-primary" />
                <StarIcon className="h-5 w-5 fill-primary" />
              </div>
            </div>
            <p className="text-sm leading-relaxed text-muted-foreground">
              "I was hesitant to try this product at first, but I'm so glad I\n did. The customer support has been
              outstanding, and the features\n have exceeded my expectations."
            </p>
          </div>
          <div className="flex flex-col items-start rounded-lg bg-card p-6 shadow-lg transition-all duration-300 hover:shadow-xl">
            <div className="mb-4 flex items-center justify-between w-full">
              <div className="flex items-center gap-2">
                <Avatar className="h-10 w-10 border">
                  <AvatarImage src="/placeholder-user.jpg" />
                  <AvatarFallback>CN</AvatarFallback>
                </Avatar>
                <div>
                  <h3 className="text-base font-semibold">Michael Chen</h3>
                  <p className="text-sm text-muted-foreground">Software Engineer, Stark Industries</p>
                </div>
              </div>
              <div className="flex items-center gap-1">
                <StarIcon className="h-5 w-5 fill-primary" />
                <StarIcon className="h-5 w-5 fill-primary" />
                <StarIcon className="h-5 w-5 fill-primary" />
                <StarIcon className="h-5 w-5 fill-primary" />
                <StarIcon className="h-5 w-5 fill-primary" />
              </div>
            </div>
            <p className="text-sm leading-relaxed text-muted-foreground">
              "This product has completely transformed the way my team\n collaborates. The intuitive interface and
              powerful features have\n made our work so much more efficient and enjoyable."
            </p>
          </div>
        </div>
      </div>
    </section>
  )
}

function StarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
